package POJO;
<<<<<<< HEAD
// Generated 19-nov-2018 23:50:58 by Hibernate Tools 4.3.1
=======
// Generated 21-nov-2018 18:39:09 by Hibernate Tools 4.3.1
>>>>>>> Julian


import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Subcategoria subcategoria;
     private Vendedor vendedor;
     private String nombreArt;
     private String descripcionArt;
     private float importeArt;
     private Date fechaAltaArt = java.sql.Date.valueOf(LocalDate.now());
     private int cantidadMaxArt;
     private Set pedidoLins = new HashSet(0);
     private Set comentarios = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(Categoria categoria, Subcategoria subcategoria, Vendedor vendedor, String nombreArt, float importeArt, Date fechaAltaArt, int cantidadMaxArt) {
        this.categoria = categoria;
        this.subcategoria = subcategoria;
        this.vendedor = vendedor;
        this.nombreArt = nombreArt;
        this.importeArt = importeArt;
        this.fechaAltaArt = fechaAltaArt;
        this.cantidadMaxArt = cantidadMaxArt;
    }
    public Articulo(Categoria categoria, Subcategoria subcategoria, Vendedor vendedor, String nombreArt, String descripcionArt, float importeArt, Date fechaAltaArt, int cantidadMaxArt, Set pedidoLins, Set comentarios) {
       this.categoria = categoria;
       this.subcategoria = subcategoria;
       this.vendedor = vendedor;
       this.nombreArt = nombreArt;
       this.descripcionArt = descripcionArt;
       this.importeArt = importeArt;
       this.fechaAltaArt = fechaAltaArt;
       this.cantidadMaxArt = cantidadMaxArt;
       this.pedidoLins = pedidoLins;
       this.comentarios = comentarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public String getNombreArt() {
        return this.nombreArt;
    }
    
    public void setNombreArt(String nombreArt) {
        this.nombreArt = nombreArt;
    }
    public String getDescripcionArt() {
        return this.descripcionArt;
    }
    
    public void setDescripcionArt(String descripcionArt) {
        this.descripcionArt = descripcionArt;
    }
    public float getImporteArt() {
        return this.importeArt;
    }
    
    public void setImporteArt(float importeArt) {
        this.importeArt = importeArt;
    }
    public Date getFechaAltaArt() {
        return this.fechaAltaArt;
    }
    
    public void setFechaAltaArt(Date fechaAltaArt) {
        this.fechaAltaArt = fechaAltaArt;
    }
    public int getCantidadMaxArt() {
        return this.cantidadMaxArt;
    }
    
    public void setCantidadMaxArt(int cantidadMaxArt) {
        this.cantidadMaxArt = cantidadMaxArt;
    }
    public Set getPedidoLins() {
        return this.pedidoLins;
    }
    
    public void setPedidoLins(Set pedidoLins) {
        this.pedidoLins = pedidoLins;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


