package POJO;
// Generated 27-oct-2018 14:07:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String nombreCat;
     private String descripcionCat;
     private Set articulos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id) {
        this.id = id;
    }
    public Categoria(int id, String nombreCat, String descripcionCat, Set articulos) {
       this.id = id;
       this.nombreCat = nombreCat;
       this.descripcionCat = descripcionCat;
       this.articulos = articulos;
    }
    
    public Categoria(String nombreCat, String descripcionCat) {
       this.nombreCat = nombreCat;
       this.descripcionCat = descripcionCat;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreCat() {
        return this.nombreCat;
    }
    
    public void setNombreCat(String nombreCat) {
        this.nombreCat = nombreCat;
    }
    public String getDescripcionCat() {
        return this.descripcionCat;
    }
    
    public void setDescripcionCat(String descripcionCat) {
        this.descripcionCat = descripcionCat;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


