package POJO;
// Generated 20-oct-2018 19:50:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int id;
     private Articulo articulo;
     private Integer idUsuarioCom;
     private String descripcionCom;
     private Integer valoracionCom;
     private Date fechaAltaCom;

    public Comentario() {
    }

	
    public Comentario(int id) {
        this.id = id;
    }
    public Comentario(int id, Articulo articulo, Integer idUsuarioCom, String descripcionCom, Integer valoracionCom, Date fechaAltaCom) {
       this.id = id;
       this.articulo = articulo;
       this.idUsuarioCom = idUsuarioCom;
       this.descripcionCom = descripcionCom;
       this.valoracionCom = valoracionCom;
       this.fechaAltaCom = fechaAltaCom;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Integer getIdUsuarioCom() {
        return this.idUsuarioCom;
    }
    
    public void setIdUsuarioCom(Integer idUsuarioCom) {
        this.idUsuarioCom = idUsuarioCom;
    }
    public String getDescripcionCom() {
        return this.descripcionCom;
    }
    
    public void setDescripcionCom(String descripcionCom) {
        this.descripcionCom = descripcionCom;
    }
    public Integer getValoracionCom() {
        return this.valoracionCom;
    }
    
    public void setValoracionCom(Integer valoracionCom) {
        this.valoracionCom = valoracionCom;
    }
    public Date getFechaAltaCom() {
        return this.fechaAltaCom;
    }
    
    public void setFechaAltaCom(Date fechaAltaCom) {
        this.fechaAltaCom = fechaAltaCom;
    }




}


