package POJO;
// Generated 22-nov-2018 20:28:48 by Hibernate Tools 4.3.1

/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private Integer id;

    public Configuracion() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


