package POJO;
// Generated 21-nov-2018 19:12:57 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String direccionTrj;
     private String poblacionTrj;
     private String paisTrj;

    public Direccion() {
    }

    public Direccion(Usuario usuario, String direccionTrj, String poblacionTrj, String paisTrj) {
       this.usuario = usuario;
       this.direccionTrj = direccionTrj;
       this.poblacionTrj = poblacionTrj;
       this.paisTrj = paisTrj;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDireccionTrj() {
        return this.direccionTrj;
    }
    
    public void setDireccionTrj(String direccionTrj) {
        this.direccionTrj = direccionTrj;
    }
    public String getPoblacionTrj() {
        return this.poblacionTrj;
    }
    
    public void setPoblacionTrj(String poblacionTrj) {
        this.poblacionTrj = poblacionTrj;
    }
    public String getPaisTrj() {
        return this.paisTrj;
    }
    
    public void setPaisTrj(String paisTrj) {
        this.paisTrj = paisTrj;
    }




}


