package POJO;
<<<<<<< HEAD
// Generated 19-nov-2018 23:50:58 by Hibernate Tools 4.3.1
=======
// Generated 21-nov-2018 18:39:09 by Hibernate Tools 4.3.1
>>>>>>> Julian



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String direccion;
<<<<<<< HEAD
     private String pais;
=======
>>>>>>> Julian
     private String poblacion;
     private String pais;

    public Direccion() {
    }

<<<<<<< HEAD
    public Direccion(Usuario usuario, String direccion, String pais, String poblacion) {
       this.usuario = usuario;
       this.direccion = direccion;
       this.pais = pais;
=======
    public Direccion(Usuario usuario, String direccion, String poblacion, String pais) {
       this.usuario = usuario;
       this.direccion = direccion;
>>>>>>> Julian
       this.poblacion = poblacion;
       this.pais = pais;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDireccion() {
        return this.direccion;
<<<<<<< HEAD
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPais() {
        return this.pais;
=======
>>>>>>> Julian
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }




}


