package POJO;
<<<<<<< HEAD
// Generated 19-nov-2018 23:50:58 by Hibernate Tools 4.3.1
=======
// Generated 21-nov-2018 18:39:09 by Hibernate Tools 4.3.1
>>>>>>> Julian


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String descripcionPed;
     private float importePed;
     private float importeTotal;
     private Date fechaPed;
     private Set pedidoLins = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Usuario usuario, float importePed, float importeTotal, Date fechaPed) {
        this.usuario = usuario;
        this.importePed = importePed;
        this.importeTotal = importeTotal;
        this.fechaPed = fechaPed;
    }
    public Pedido(Usuario usuario, String descripcionPed, float importePed, float importeTotal, Date fechaPed, Set pedidoLins) {
       this.usuario = usuario;
       this.descripcionPed = descripcionPed;
       this.importePed = importePed;
       this.importeTotal = importeTotal;
       this.fechaPed = fechaPed;
       this.pedidoLins = pedidoLins;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcionPed() {
        return this.descripcionPed;
    }
    
    public void setDescripcionPed(String descripcionPed) {
        this.descripcionPed = descripcionPed;
    }
    public float getImportePed() {
        return this.importePed;
    }
    
    public void setImportePed(float importePed) {
        this.importePed = importePed;
    }
    public float getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(float importeTotal) {
        this.importeTotal = importeTotal;
    }
    public Date getFechaPed() {
        return this.fechaPed;
    }
    
    public void setFechaPed(Date fechaPed) {
        this.fechaPed = fechaPed;
    }
    public Set getPedidoLins() {
        return this.pedidoLins;
    }
    
    public void setPedidoLins(Set pedidoLins) {
        this.pedidoLins = pedidoLins;
    }




}


