package POJO;
// Generated 21-nov-2018 18:39:09 by Hibernate Tools 4.3.1



/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String descripcionPed;
     private float importePed;
     private float importeTotal;

    public Pedido() {
    }

    public Pedido(Usuario usuario, String descripcionPed, float importePed, float importeTotal) {
       this.usuario = usuario;
       this.descripcionPed = descripcionPed;
       this.importePed = importePed;
       this.importeTotal = importeTotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcionPed() {
        return this.descripcionPed;
    }
    
    public void setDescripcionPed(String descripcionPed) {
        this.descripcionPed = descripcionPed;
    }
    public float getImportePed() {
        return this.importePed;
    }
    
    public void setImportePed(float importePed) {
        this.importePed = importePed;
    }
    public float getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(float importeTotal) {
        this.importeTotal = importeTotal;
    }




}


