package POJO;
<<<<<<< HEAD
// Generated 19-nov-2018 23:50:58 by Hibernate Tools 4.3.1
=======
// Generated 21-nov-2018 18:39:09 by Hibernate Tools 4.3.1
>>>>>>> Julian


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer id;
<<<<<<< HEAD
     private Categoria categoria;
=======
     private String descripcionSubcat;
>>>>>>> Julian
     private String nombreSubcat;
     private String descripcionSubcat;
     private Set articulos = new HashSet(0);

    public Subcategoria() {
    }

	
<<<<<<< HEAD
    public Subcategoria(Categoria categoria, String nombreSubcat) {
        this.categoria = categoria;
        this.nombreSubcat = nombreSubcat;
    }
    public Subcategoria(Categoria categoria, String nombreSubcat, String descripcionSubcat, Set articulos) {
       this.categoria = categoria;
=======
    public Subcategoria(String descripcionSubcat, String nombreSubcat) {
        this.descripcionSubcat = descripcionSubcat;
        this.nombreSubcat = nombreSubcat;
    }
    public Subcategoria(String descripcionSubcat, String nombreSubcat, Set articulos) {
       this.descripcionSubcat = descripcionSubcat;
>>>>>>> Julian
       this.nombreSubcat = nombreSubcat;
       this.descripcionSubcat = descripcionSubcat;
       this.articulos = articulos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
<<<<<<< HEAD
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
=======
    public String getDescripcionSubcat() {
        return this.descripcionSubcat;
    }
    
    public void setDescripcionSubcat(String descripcionSubcat) {
        this.descripcionSubcat = descripcionSubcat;
>>>>>>> Julian
    }
    public String getNombreSubcat() {
        return this.nombreSubcat;
    }
    
    public void setNombreSubcat(String nombreSubcat) {
        this.nombreSubcat = nombreSubcat;
    }
    public String getDescripcionSubcat() {
        return this.descripcionSubcat;
    }
    
    public void setDescripcionSubcat(String descripcionSubcat) {
        this.descripcionSubcat = descripcionSubcat;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


