package POJO;
// Generated 27-oct-2018 14:07:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private int id;
     private String nombreSubcat;
     private String descripcionSubcat;
     private Set articulos = new HashSet(0);

    public Subcategoria() {
    }

	
    public Subcategoria(int id) {
        this.id = id;
    }
    public Subcategoria(int id, String nombreSubcat, String descripcionSubcat, Set articulos) {
       this.id = id;
       this.nombreSubcat = nombreSubcat;
       this.descripcionSubcat = descripcionSubcat;
       this.articulos = articulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreSubcat() {
        return this.nombreSubcat;
    }
    
    public void setNombreSubcat(String nombreSubcat) {
        this.nombreSubcat = nombreSubcat;
    }
    public String getDescripcionSubcat() {
        return this.descripcionSubcat;
    }
    
    public void setDescripcionSubcat(String descripcionSubcat) {
        this.descripcionSubcat = descripcionSubcat;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


