package POJO;
// Generated 25-nov-2018 17:56:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String numeroTarj;
     private int mesCadTarj;
     private int annoCadTarj;
     private Set pedidos = new HashSet(0);

    public Tarjeta() {
    }

	
    public Tarjeta(Usuario usuario, String numeroTarj, int mesCadTarj, int annoCadTarj) {
        this.usuario = usuario;
        this.numeroTarj = numeroTarj;
        this.mesCadTarj = mesCadTarj;
        this.annoCadTarj = annoCadTarj;
    }
    public Tarjeta(Usuario usuario, String numeroTarj, int mesCadTarj, int annoCadTarj, Set pedidos) {
       this.usuario = usuario;
       this.numeroTarj = numeroTarj;
       this.mesCadTarj = mesCadTarj;
       this.annoCadTarj = annoCadTarj;
       this.pedidos = pedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNumeroTarj() {
        return this.numeroTarj;
    }
    
    public void setNumeroTarj(String numeroTarj) {
        this.numeroTarj = numeroTarj;
    }
    public int getMesCadTarj() {
        return this.mesCadTarj;
    }
    
    public void setMesCadTarj(int mesCadTarj) {
        this.mesCadTarj = mesCadTarj;
    }
    public int getAnnoCadTarj() {
        return this.annoCadTarj;
    }
    
    public void setAnnoCadTarj(int annoCadTarj) {
        this.annoCadTarj = annoCadTarj;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


