package POJO;
// Generated 19-oct-2018 11:32:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nifUsr;
     private String passUsr;
     private String nombreUsr;
     private String apellido1Usr;
     private String apellido2Usr;
     private String emailUsr;
     private Date fechaAltaUsr;
     private Date fechaNacUsr;
     private Set pedidos = new HashSet(0);
     private Set tarjetas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String nifUsr, String passUsr) {
        this.id = id;
        this.nifUsr = nifUsr;
        this.passUsr = passUsr;
    }
    public Usuario(int id, String nifUsr, String passUsr, String nombreUsr, String apellido1Usr, String apellido2Usr, String emailUsr, Date fechaAltaUsr, Date fechaNacUsr, Set pedidos, Set tarjetas) {
       this.id = id;
       this.nifUsr = nifUsr;
       this.passUsr = passUsr;
       this.nombreUsr = nombreUsr;
       this.apellido1Usr = apellido1Usr;
       this.apellido2Usr = apellido2Usr;
       this.emailUsr = emailUsr;
       this.fechaAltaUsr = fechaAltaUsr;
       this.fechaNacUsr = fechaNacUsr;
       this.pedidos = pedidos;
       this.tarjetas = tarjetas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNifUsr() {
        return this.nifUsr;
    }
    
    public void setNifUsr(String nifUsr) {
        this.nifUsr = nifUsr;
    }
    public String getPassUsr() {
        return this.passUsr;
    }
    
    public void setPassUsr(String passUsr) {
        this.passUsr = passUsr;
    }
    public String getNombreUsr() {
        return this.nombreUsr;
    }
    
    public void setNombreUsr(String nombreUsr) {
        this.nombreUsr = nombreUsr;
    }
    public String getApellido1Usr() {
        return this.apellido1Usr;
    }
    
    public void setApellido1Usr(String apellido1Usr) {
        this.apellido1Usr = apellido1Usr;
    }
    public String getApellido2Usr() {
        return this.apellido2Usr;
    }
    
    public void setApellido2Usr(String apellido2Usr) {
        this.apellido2Usr = apellido2Usr;
    }
    public String getEmailUsr() {
        return this.emailUsr;
    }
    
    public void setEmailUsr(String emailUsr) {
        this.emailUsr = emailUsr;
    }
    public Date getFechaAltaUsr() {
        return this.fechaAltaUsr;
    }
    
    public void setFechaAltaUsr(Date fechaAltaUsr) {
        this.fechaAltaUsr = fechaAltaUsr;
    }
    public Date getFechaNacUsr() {
        return this.fechaNacUsr;
    }
    
    public void setFechaNacUsr(Date fechaNacUsr) {
        this.fechaNacUsr = fechaNacUsr;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set tarjetas) {
        this.tarjetas = tarjetas;
    }




}


