package POJO;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nifUsr;
     private String passUsr;
     private String nombreUsr;
     private String apellidoUsr;
     private String emailUsr;
     private Date fechaAltaUsr;
     private Date fechaNacUsr;
     private Set comentarios = new HashSet(0);
     private Set direccions = new HashSet(0);
     private Set tarjetas = new HashSet(0);
     private Set pedidos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nifUsr, String passUsr, String nombreUsr, String apellidoUsr, String emailUsr, Date fechaAltaUsr, Date fechaNacUsr) {
        this.nifUsr = nifUsr;
        this.passUsr = passUsr;
        this.nombreUsr = nombreUsr;
        this.apellidoUsr = apellidoUsr;
        this.emailUsr = emailUsr;
        this.fechaAltaUsr = fechaAltaUsr;
        this.fechaNacUsr = fechaNacUsr;
    }
    public Usuario(String nifUsr, String passUsr, String nombreUsr, String apellidoUsr, String emailUsr, Date fechaAltaUsr, Date fechaNacUsr, Set comentarios, Set direccions, Set tarjetas, Set pedidos) {
       this.nifUsr = nifUsr;
       this.passUsr = passUsr;
       this.nombreUsr = nombreUsr;
       this.apellidoUsr = apellidoUsr;
       this.emailUsr = emailUsr;
       this.fechaAltaUsr = fechaAltaUsr;
       this.fechaNacUsr = fechaNacUsr;
       this.comentarios = comentarios;
       this.direccions = direccions;
       this.tarjetas = tarjetas;
       this.pedidos = pedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNifUsr() {
        return this.nifUsr;
    }
    
    public void setNifUsr(String nifUsr) {
        this.nifUsr = nifUsr;
    }
    public String getPassUsr() {
        return this.passUsr;
    }
    
    public void setPassUsr(String passUsr) {
        this.passUsr = passUsr;
    }
    public String getNombreUsr() {
        return this.nombreUsr;
    }
    
    public void setNombreUsr(String nombreUsr) {
        this.nombreUsr = nombreUsr;
    }
    public String getApellidoUsr() {
        return this.apellidoUsr;
    }
    
    public void setApellidoUsr(String apellidoUsr) {
        this.apellidoUsr = apellidoUsr;
    }
    public String getEmailUsr() {
        return this.emailUsr;
    }
    
    public void setEmailUsr(String emailUsr) {
        this.emailUsr = emailUsr;
    }
    public Date getFechaAltaUsr() {
        return this.fechaAltaUsr;
    }
    
    public void setFechaAltaUsr(Date fechaAltaUsr) {
        this.fechaAltaUsr = fechaAltaUsr;
    }
    public Date getFechaNacUsr() {
        return this.fechaNacUsr;
    }
    
    public void setFechaNacUsr(Date fechaNacUsr) {
        this.fechaNacUsr = fechaNacUsr;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }
    public Set getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set tarjetas) {
        this.tarjetas = tarjetas;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


