package POJO;
// Generated 20-oct-2018 19:50:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int id;
     private String nifVend;
     private String passVend;
     private String nombreVend;
     private String apellido1Vend;
     private String emailVend;
     private String apellido2Vend;
     private Date fechaAltaVend;
     private Date fechaNacVend;
     private Set articulos = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(int id, String nifVend) {
        this.id = id;
        this.nifVend = nifVend;
    }
    public Vendedor(int id, String nifVend, String passVend, String nombreVend, String apellido1Vend, String emailVend, String apellido2Vend, Date fechaAltaVend, Date fechaNacVend, Set articulos) {
       this.id = id;
       this.nifVend = nifVend;
       this.passVend = passVend;
       this.nombreVend = nombreVend;
       this.apellido1Vend = apellido1Vend;
       this.emailVend = emailVend;
       this.apellido2Vend = apellido2Vend;
       this.fechaAltaVend = fechaAltaVend;
       this.fechaNacVend = fechaNacVend;
       this.articulos = articulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNifVend() {
        return this.nifVend;
    }
    
    public void setNifVend(String nifVend) {
        this.nifVend = nifVend;
    }
    public String getPassVend() {
        return this.passVend;
    }
    
    public void setPassVend(String passVend) {
        this.passVend = passVend;
    }
    public String getNombreVend() {
        return this.nombreVend;
    }
    
    public void setNombreVend(String nombreVend) {
        this.nombreVend = nombreVend;
    }
    public String getApellido1Vend() {
        return this.apellido1Vend;
    }
    
    public void setApellido1Vend(String apellido1Vend) {
        this.apellido1Vend = apellido1Vend;
    }
    public String getEmailVend() {
        return this.emailVend;
    }
    
    public void setEmailVend(String emailVend) {
        this.emailVend = emailVend;
    }
    public String getApellido2Vend() {
        return this.apellido2Vend;
    }
    
    public void setApellido2Vend(String apellido2Vend) {
        this.apellido2Vend = apellido2Vend;
    }
    public Date getFechaAltaVend() {
        return this.fechaAltaVend;
    }
    
    public void setFechaAltaVend(Date fechaAltaVend) {
        this.fechaAltaVend = fechaAltaVend;
    }
    public Date getFechaNacVend() {
        return this.fechaNacVend;
    }
    
    public void setFechaNacVend(Date fechaNacVend) {
        this.fechaNacVend = fechaNacVend;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


